services:
  db_diff_backup:
    image: mysql:8
    container_name: db_diff_backup
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
      - ./backups/diff:/backup
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=books
      - MYSQL_PASSWORD=admin

volumes:
  db_volume: {}
